#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || (cd "$script_dir/.." && pwd))"

"$root_dir/tools/test_goals_scorecard_v01.sh"
"$root_dir/tools/test_phased_plan_v01_v03.sh"
"$root_dir/tools/test_coding_readiness_gate.sh"
"$root_dir/tools/test_doc_test_harness_standardization.sh"
"$root_dir/tools/test_readme_v01_alignment.sh"
"$root_dir/tools/test_docs_navigation_hardening.sh"
"$root_dir/tools/test_founder_operator_workflow.sh"
"$root_dir/tools/test_qa_regression_rubric.sh"
"$root_dir/tools/test_state_transition_checklist.sh"
"$root_dir/tools/test_launch_stage_readme_queue.sh"
"$root_dir/tools/test_launch_stage_memory_integration.sh"
"$root_dir/tools/test_memory_snapshot_plan.sh"
"$root_dir/tools/test_dogfood_scenario_pack_v01.sh"
"$root_dir/tools/test_dogfood_semantic_hardening_v01.sh"
"$root_dir/tools/test_kpi_snapshot_baseline_v01.sh"
"$root_dir/tools/test_kpi_snapshot_delta_post_hardening_v01.sh"
"$root_dir/tools/test_release_checkpoint_bundle_v01.sh"
"$root_dir/tools/test_humans_agents_sync.sh"
"$root_dir/tools/test_intake_validation.sh"
"$root_dir/tools/test_validate_intake_duplicate_ids.sh"
"$root_dir/tools/test_program_state_consistency.sh"
"$root_dir/tools/test_stage_exit_pipeline.sh"
"$root_dir/tools/test_go_toolchain_readiness.sh"
"$root_dir/tools/test_observer_cycle_policy.sh"
"$root_dir/tools/test_observer_cycle_memory_integration.sh"
