{
  "schema_version": "1.0",
  "id": "product-vision-f02a617c",
  "title": "Product Vision F02a617c",
  "status": "approved",
  "updated_at": "2026-02-23T04:55:28Z",
  "review": {
    "reviewed_by": "system",
    "reviewed_at": "2026-02-23T04:55:28Z",
    "decision": "approved",
    "decision_notes": "automated crawl"
  }
}
